# Generated by Django 5.1.3 on 2024-12-01 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0003_skill_remove_cv_ai_recommendation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='isverified',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
