# Generated by Django 5.1.3 on 2024-12-01 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0004_profile_isverified'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='pmc_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
